name: ping
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: install dependencies
        run: npm ci

      - name: run go-chat supabase keepalive script
        env:
          GO_CHAT_SUPABASE_API_URL: ${{ secrets.GO_CHAT_SUPABASE_API_URL }}
          GO_CHAT_SUPABASE_ANON_KEY: ${{ secrets.GO_CHAT_SUPABASE_ANON_KEY }}
        run: npx tsx go-chat/supabase_keepalive.ts

      - name: ping go-chat backend
        run: curl -f https://go-chat-56oc.onrender.com/api/healthcheck
